### ISSUE TITLE
Use Tailwind and use same config as snapshot main repo

### ISSUE THREAD

**Issue by jm90m** [snapshot-labs/snapshot-app#11]
Tailwind is already added as a dependency - https://github.com/vadimdemedes/tailwind-rn

All that is needed is to use the following config here:
- https://github.com/snapshot-labs/snapshot/blob/develop/tailwind.config.js

And generate the styles.json
![Screen Shot 2021-10-14 at 10 54 59 AM](https://user-images.githubusercontent.com/5067716/137343149-7a014171-178f-470b-b308-7f2dd27fde9b.png)

**Comment by aiinkiestism** [comment]
I may work on this.

**Comment by aiinkiestism** [comment]
@jm90m 
You removed tailwind from this repo but is this task is still active?

**Comment by jm90m** [comment]
@aiinkiestism This task is no longer active, we wont use tailwind for mobile
